/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import javax.swing.JOptionPane;

/**
 *
 * @author USER
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainPanel = new javax.swing.JPanel();
        Title = new javax.swing.JLabel();
        FnameLabel = new javax.swing.JLabel();
        LnameLabel = new javax.swing.JLabel();
        AgeLabel = new javax.swing.JLabel();
        EmailLabel = new javax.swing.JLabel();
        MessageLabel = new javax.swing.JLabel();
        FnameTxtField = new javax.swing.JTextField();
        LnameTxtField = new javax.swing.JTextField();
        AgeTxtField = new javax.swing.JTextField();
        EmailTxtField = new javax.swing.JTextField();
        MessageTxtFIeld = new javax.swing.JTextField();
        Submitbutton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        MainPanel.setBackground(new java.awt.Color(255, 255, 204));

        Title.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        Title.setText("Customer Registration Form");

        FnameLabel.setText("First Name");

        LnameLabel.setText("Last Name");

        AgeLabel.setText("Age");

        EmailLabel.setText("Email");

        MessageLabel.setText("Message");

        FnameTxtField.setText(" ");
        FnameTxtField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                FnameTxtFieldFocusLost(evt);
            }
        });

        LnameTxtField.setText(" ");
        LnameTxtField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                LnameTxtFieldFocusLost(evt);
            }
        });

        AgeTxtField.setText(" ");
        AgeTxtField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                AgeTxtFieldFocusLost(evt);
            }
        });

        EmailTxtField.setText(" ");
        EmailTxtField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                EmailTxtFieldFocusLost(evt);
            }
        });

        MessageTxtFIeld.setText(" ");

        Submitbutton.setText("Submit");
        Submitbutton.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                SubmitbuttonFocusLost(evt);
            }
        });
        Submitbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitbuttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MainPanelLayout = new javax.swing.GroupLayout(MainPanel);
        MainPanel.setLayout(MainPanelLayout);
        MainPanelLayout.setHorizontalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainPanelLayout.createSequentialGroup()
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MainPanelLayout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addComponent(Title, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(MainPanelLayout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(FnameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(EmailLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)
                                    .addComponent(AgeLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addComponent(MessageLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(LnameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(130, 130, 130)
                        .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(FnameTxtField)
                            .addComponent(LnameTxtField)
                            .addComponent(AgeTxtField)
                            .addComponent(EmailTxtField)
                            .addComponent(MessageTxtFIeld, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)))
                    .addGroup(MainPanelLayout.createSequentialGroup()
                        .addGap(174, 174, 174)
                        .addComponent(Submitbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        MainPanelLayout.setVerticalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainPanelLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(Title, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FnameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FnameTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LnameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LnameTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AgeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AgeTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EmailLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EmailTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(MessageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MessageTxtFIeld, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addComponent(Submitbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SubmitbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitbuttonActionPerformed
        // TODO add your handling code here:
        String Fname = FnameTxtField.getText();
        String Lname = LnameTxtField.getText();
        String age   = AgeTxtField.getText();
        String email = EmailTxtField.getText();
        
        if (Fname.trim().isEmpty()||Lname.trim().isEmpty()||age.trim().isEmpty()|| email.trim().isEmpty())
        {
            JOptionPane.showMessageDialog(this, "Please fill in all the details", "Incomplete Form", JOptionPane.ERROR_MESSAGE);            
            return;        
        }  
        else
        {
        System.out.println("First name: " + Fname);
        System.out.println("Last name: " + Lname);
        System.out.println("Age: " + age);
        System.out.println("Email: " + email);
        JOptionPane.showMessageDialog(null, "Registration successful!");
    }//GEN-LAST:event_SubmitbuttonActionPerformed
    }
        
    private void FnameTxtFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_FnameTxtFieldFocusLost
        // TODO add your handling code here:
        String Fname = FnameTxtField.getText();
        if(!isValidName(Fname))
        {
            JOptionPane.showMessageDialog(this, "Invalid First Name", "Wrong Input", JOptionPane.ERROR_MESSAGE);
            FnameTxtField.requestFocus();
        }
    }//GEN-LAST:event_FnameTxtFieldFocusLost

    private void LnameTxtFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_LnameTxtFieldFocusLost
        // TODO add your handling code here:
        String Lname = LnameTxtField.getText();
        if(!isValidName(Lname))
        {
            JOptionPane.showMessageDialog(this, "Invalid Last Name", "Wrong Input", JOptionPane.ERROR_MESSAGE);
            LnameTxtField.requestFocus();
        }
    }//GEN-LAST:event_LnameTxtFieldFocusLost

    private void AgeTxtFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_AgeTxtFieldFocusLost
        // TODO add your handling code here:
        String age = AgeTxtField.getText().trim();
        if(!age.isEmpty() && !isValidInteger(age))
        {
            JOptionPane.showMessageDialog(this, "Invalid Age", "Wrong Input", JOptionPane.ERROR_MESSAGE);
            AgeTxtField.requestFocus();
        }
    }//GEN-LAST:event_AgeTxtFieldFocusLost

    private void EmailTxtFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_EmailTxtFieldFocusLost
        // TODO add your handling code here:
        String email = EmailTxtField.getText();
        if(!isValidEmail(email))
         {
            JOptionPane.showMessageDialog(this, "Please provide proper Email Address", "Wrong Input", JOptionPane.ERROR_MESSAGE);
            EmailTxtField.requestFocus();
        }
    }//GEN-LAST:event_EmailTxtFieldFocusLost

    private void SubmitbuttonFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_SubmitbuttonFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_SubmitbuttonFocusLost

    private boolean isValidEmail(String email)
    {
        if (email.isEmpty() || email.trim().isEmpty()){
        return true; // Empty email is accepted
        }
        return email.matches("^[\\w-\\.]+@([\\w-]+\\.)+[\\w-]{2,4}$");
    }
    
    private boolean isValidName(String name)
    {
        return name.matches("^$|^[A-Za-z\\s]+$");
    }
    
    private boolean isValidInteger(String age)
    {        
    {
       if (age.isEmpty() || age == null) {
            return true; // Empty string is accepted
        }

        try {
            int ageint = Integer.parseInt(age);

            // Check if the age is within a valid range
            if (ageint >= 0 && ageint <= 150) {
                return true; // Valid age
            } else {
                return false; // Age is out of range
            }
        } catch (NumberFormatException e) {
            return false; // Not a valid integer
        }
    } 
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AgeLabel;
    private javax.swing.JTextField AgeTxtField;
    private javax.swing.JLabel EmailLabel;
    private javax.swing.JTextField EmailTxtField;
    private javax.swing.JLabel FnameLabel;
    private javax.swing.JTextField FnameTxtField;
    private javax.swing.JLabel LnameLabel;
    private javax.swing.JTextField LnameTxtField;
    private javax.swing.JPanel MainPanel;
    private javax.swing.JLabel MessageLabel;
    private javax.swing.JTextField MessageTxtFIeld;
    private javax.swing.JButton Submitbutton;
    private javax.swing.JLabel Title;
    // End of variables declaration//GEN-END:variables
}
